### PR TITLE
Course ids fix

### PR DESCRIPTION
**Pull request by AbdouSeck**
Changes:

1) Inside file `make_grades_persistent.py`
Added fix_course_ids to change course ids to their expected format in `make_grades_persistent.py`

2) Changed `remove_nulls_from_grade_persistent` to `cleanup_rows_from_grade_persistent` in `make_grades_persistent.py` to make it a more general function.

***Note***:
I also noticed the call to `make_grades_persistent.already_exists` in `main.py`, but there is no `already_exists` function defined in `make_grades_persistent.py`. This could cause errors in the future. @lstmemery, is this trying to access the same function defined in `make_grading_policy_table.py`?

### CODE REVIEW

**Comment by lstmemery** [comment]
You are correct. It should be `make_grading_policy_table.already_exists`, not `make_grades_persistent.already_exists.` This was the result of a sloppy refactoring on my part. Could you please correct my mistake?

**Comment by AbdouSeck** [comment]
@lstmemery the function should now be accessed from the right module. Thanks!

**Comment by ichuang** [comment]
Thanks Abdou!

BTW, note that `fix_course_ids()` need not return the dict (and the call need not replace `row_dict`), because `row_dict` is passed by reference and modifications happen in-place.

**Comment by AbdouSeck** [comment]
I just picked up on that. I am always trying to avoid doing anything by reference in python. But this won't cause much damage other than time wasted assigning `row_dict` back to itself. I'll fix it next time something comes up. Thanks!

**Pull request merged**
